server:
  port: 3000
  port.http: 8080
  ssl:
    enable: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 12341234
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prodytalk-db.cxe3wlhwdbsi.us-east-1.rds.amazonaws.com:3306/prodytalk?serverTimezone=UTC&characterEncoding=UTF-8
    username: twomandarin
    password: 12341234
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

mybatis:
  config-location: classpath:MyBatisConfig.xml
  multiple-result-sets-enabled: false
  map-underscore-to-camel-case: true
  call-setters-on-nulls: true
  jdbc-type-for-null: varchar
  default-fetch-size: 500
  mapper-locations: classpath:mybatis/*.xml

jwt:
  password: testPassword